#builds and runs tests (if any)
name: build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal
  create-tag-and-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: rymndhng/release-on-push-action@master
      id: release-on-push
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }} # tag only pushes to the master branch
      with:
        bump_version_scheme: minor
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      tag_name: ${{ steps.release-on-push.outputs.tag_name }}
  packageapp:
    needs: create-tag-and-release
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ needs.create-tag-and-release.outputs.tag_name }}
        fetch-depth: 0 #needed to get the tags for proper versioning. Also note at this point we expect the commit to be tagged by the build.
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Generate app files
      run: dotnet publish -c Release
    - uses: actions/upload-artifact@v4 # make the files available to next action that will zip and release the app from linux
      with:
        name: appfiles
        path: SpindleTalkerDialog/bin/Release/net8.0-windows/publish/
    - name: publish VfdControl to nuget #only when building on master and when tagging
      if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/master') || startsWith(github.ref, 'refs/tags') }}
      run: dotnet nuget push VfdControl\bin\Release\*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.CA_NUGET_PACKAGES_KEY }}
    outputs:
      tag_name: ${{ needs.create-tag-and-release.outputs.tag_name }}
  release:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }} # only create releases on pushes to the master branch
    needs: packageapp
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/download-artifact@v4 # make the files available to next action that will zip and release the app from linux
      with:
        name: appfiles
    - name: Install zip
      uses: montudor/action-zip@c25e01d7489d0274569440a2f0281b4569df16bc
    - name: Zip app files
      run: zip -qq -r SpindleTalker.zip *
    - name: Release
      uses: softprops/action-gh-release@affa18ef97bc9db20076945705aba8c516139abd
      with:
        files: '*.zip'
        tag_name: ${{ needs.packageapp.outputs.tag_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
